import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {site,projects,engineering,awards,otherResults,documents} from '../content/site.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8').replace(/^\uFEFF/,''));
const media=read('content/gallery.json');
const out=path.join(root,'public');
fs.mkdirSync(out,{recursive:true});
const VERSION='20261008-r3';
const escape=v=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const l=(zh,en)=>({zh,en});
const t=(zh,en)=>{const v=typeof zh==='object'?zh:l(zh,en);return `<span class="lang-zh">${escape(v.zh)}</span><span class="lang-en" lang="en">${escape(v.en)}</span>`};
const attr=(name,zh,en)=>`${name}="${escape(zh)}" data-zh-${name}="${escape(zh)}" data-en-${name}="${escape(en)}"`;
const arrow='<span class="arrow" aria-hidden="true">↗</span>';
const button=(label,href,extra='')=>`<a class="button" href="${href}" ${extra}>${t(label)}${arrow}</a>`;
const external=(label,href)=>button(label,href,'target="_blank" rel="noopener noreferrer"');
const heading=(label,tag='h2',cls='')=>`<${tag}${cls?` class="${cls}"`:''}>${t(label)}</${tag}>`;
const para=(label,cls='')=>`<p${cls?` class="${cls}"`:''}>${t(label)}</p>`;
const note=(label)=>para(label,'note');
const section=(id,label,body,extra='')=>`<section class="content-section ${extra}" id="${id}"><div class="container">${heading(label)}${body}</div></section>`;
const actions=html=>`<div class="actions">${html}</div>`;
const itemsById=Object.fromEntries(media.items.map(i=>[i.id,i]));
const toKb=n=>(n/1024).toFixed(0)+' KB';
const toMb=n=>(n/1048576).toFixed(1)+' MB';
const img=(src,alt,extra='')=>`<img src="${src}" ${attr('alt',alt.zh,alt.en)} decoding="async" ${extra}>`;
const photo=(item,cls='',eager=false)=>img(item.src,item.title,`class="${cls}" width="${item.width}" height="${item.height}" srcset="${item.srcset}" sizes="(max-width: 760px) 94vw, 55vw" loading="${eager?'eager':'lazy'}"`);
const cover=(name,position='center',eager=false)=>`<picture class="scene-background" style="--image-position:${position}"><img src="assets/covers/${name}-1600.webp" srcset="assets/covers/${name}-900.webp 900w, assets/covers/${name}-1600.webp 1600w${name==='calculator'?'':`, assets/covers/${name}-2400.webp 2400w`}" sizes="100vw" alt="" width="1920" height="1280" loading="${eager?'eager':'lazy'}" ${eager?'fetchpriority="high"':''}></picture>`;
const scenePhoto=(item,eager=false)=>`<picture class="scene-background">${img(item.src,l('',''),`srcset="${item.srcset}" sizes="100vw" width="${item.width}" height="${item.height}" loading="${eager?'eager':'lazy'}"`)}</picture>`;
const crumbs=(parent,href,current)=>`<nav class="breadcrumbs" ${attr('aria-label','面包屑导航','Breadcrumbs')}><a href="index.html">${t('首页','Home')}</a><span aria-hidden="true">/</span><a href="${href}">${t(parent)}</a><span aria-hidden="true">/</span><span>${t(current)}</span></nav>`;

function navigation() {
 return `<a class="skip-link" href="#main">${t('跳到正文','Skip to content')}</a>
<header class="site-header" id="site-header"><div class="nav-shell">
 <a class="site-mark" href="index.html" ${attr('aria-label','孔一宸 · 首页','Yichen Kong · Home')}>${img('assets/covers/logo.webp',l('个人标志','Personal logo'),'width="789" height="497" fetchpriority="high"')}</a>
 <nav id="site-menu" class="site-menu" ${attr('aria-label','主导航','Main navigation')}>
  <a class="nav-link" href="index.html#about">${t('个人简介','About')}</a>
  <div class="nav-group" data-nav-group><button class="nav-disclosure" aria-expanded="false" aria-controls="project-menu">${t('项目','Projects')}<i class="chevron" aria-hidden="true"></i></button>
    <div class="sub-menu" id="project-menu">${projects.map(p=>`<a href="${p.href}">${t(p.title)}</a>`).join('')}</div>
  </div>
  <a class="nav-link" href="awards.html">${t('成果与荣誉','Recognition')}</a>
  <div class="nav-group" data-nav-group><button class="nav-disclosure" aria-expanded="false" aria-controls="place-menu">${t('青海','Qinghai')}<i class="chevron" aria-hidden="true"></i></button>
    <div class="sub-menu" id="place-menu"><a href="qinghai.html">${t('青海省','Qinghai province')}</a><a href="tuotuohe.html">${t('沱沱河','Tuotuohe')}</a><a href="qinghai.html#albums">${t('摄影图册','Photo albums')}</a></div>
  </div>
  <a class="nav-link" href="discussion.html">${t('留言与讨论','Discussion')}</a><a class="nav-link" href="index.html#contact">${t('联系','Contact')}</a>
 </nav>
 <div class="nav-tools"><button class="language-toggle" data-language-toggle ${attr('aria-label','切换为英文','Switch to Chinese')}><span data-lang-code="zh">中</span><span aria-hidden="true"> / </span><span data-lang-code="en">EN</span></button>
 <button class="menu-toggle" aria-controls="site-menu" aria-expanded="false" ${attr('aria-label','打开导航菜单','Open navigation menu')}><span></span><span></span></button></div>
</div></header>`;
}
function dialogs() {
 return `<dialog class="info-dialog" id="wechat-dialog" aria-labelledby="wechat-title">
 <button class="dialog-close" data-close-dialog ${attr('aria-label','关闭','Close')}>×</button>
 ${heading(l('添加微信','Add on WeChat'),'h2','dialog-title').replace('<h2','<h2 id="wechat-title"')}
 ${para(l('在微信的「添加朋友」中搜索下方号码。普通网页不能通过手机号直接打开加好友页面。','Search for this number in WeChat → Add contacts. A normal webpage cannot open a person’s add-contact page using a phone number.'))}
 <code class="contact-code">13997320897</code><button class="button" data-copy="13997320897">${t('复制微信号','Copy WeChat ID')}</button>
 <p class="copy-feedback" role="status" aria-live="polite"></p></dialog>
 <dialog class="info-dialog" id="radio-dialog" aria-labelledby="radio-title"><button class="dialog-close" data-close-dialog ${attr('aria-label','关闭','Close')}>×</button>
 <h2 id="radio-title">${site.callsign}</h2>${para(l('业余无线电台呼号','Amateur-radio callsign'),'eyebrow')}
 <dl class="radio-definition"><dt>B</dt><dd>${t('中国的无线电呼号前缀。','A radio callsign prefix allocated to China.')}</dd>
 <dt>G</dt><dd>${t('中国大陆业余电台使用的呼号系列字母；不据此推断当前操作等级。','A letter in a mainland Chinese amateur-radio callsign series; it does not establish the current operator class.')}</dd>
 <dt>9</dt><dd>${t('第九分区：陕西、甘肃、宁夏和青海。','Call area 9: Shaanxi, Gansu, Ningxia and Qinghai.')}</dd>
 <dt>SOE</dt><dd>${t('用于区分电台的后缀，位于青海分配范围 SAA–XZZ 内。此处 O 是字母，不是数字 0。','The station-identifying suffix, within Qinghai’s allocated SAA–XZZ range. O is the letter, not the digit zero.')}</dd></dl>
 ${note(l('本站电台所在地：中国 · 青海省 · 西宁市。呼号字母含义不等于无线电执照的全部信息。','Station location: Xining, Qinghai, China. A callsign does not describe every condition of a radio licence.'))}
 <p class="note"><a href="https://www.miit.gov.cn/cms_files/filemanager/1226211233/attach/20238/e3a97cec523441028cc51de62886101c.pdf" target="_blank" rel="noopener">${t('来源：工信部业余无线电台呼号规则','Source: MIIT amateur-radio callsign rules')} ↗</a></p></dialog>
 <dialog class="panorama-dialog" id="panorama-dialog" aria-labelledby="panorama-title"><header><h2 id="panorama-title">${t('西宁全景','Xining panorama')}</h2><button class="dialog-close" data-close-dialog ${attr('aria-label','关闭全景','Close panorama')}>×</button></header><div id="panorama-viewer"></div><div class="panorama-tools"><button data-panorama="in">${t('放大','Zoom in')}</button><button data-panorama="out">${t('缩小','Zoom out')}</button><button data-panorama="home">${t('全景','Fit image')}</button><a id="panorama-original" href="${itemsById['xining-panorama'].original.url}" target="_blank" rel="noopener">${t('查看原图','View original')} · 162 MB ↗</a></div>${note(l('最高层保留 28,800 × 14,400 分辨率。拖动、双指或滚轮缩放，按需加载图像分块。','Full-resolution level: 28,800 × 14,400. Drag, pinch or use the wheel to zoom; image tiles load on demand.'))}</dialog>`;
}
function footer(){return `<footer class="site-footer"><a href="index.html">© 2026 ${t(site.name)}</a><div><a href="resume.html">${t('简历','CV')}</a><a href="documents.html">${t('研究资料','Documents')}</a><a href="sources.html">${t('图源与说明','Sources & notes')}</a></div></footer>`}
const pages=[];
function page(file,title,body,{home=false,desc,extraHead=''}={}) {
 const html=`<!doctype html>
<html lang="zh-CN" data-lang="zh"${home?' class="home-page"':''}>
<head>
 <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
 <title>${escape(title.zh)} | Yichen Kong</title>
 <meta name="description" content="${escape(desc?.zh||title.zh)}">
 <meta name="theme-color" content="#030507"><meta name="color-scheme" content="dark">
 <meta property="og:title" content="${escape(title.zh)} | Yichen Kong"><meta property="og:image" content="https://yichen-kong.github.io/assets/covers/logo.webp"><meta property="og:type" content="website">
 <link rel="canonical" href="https://yichen-kong.github.io/${file==='index.html'?'':file}">
 <link rel="icon" href="assets/covers/favicon.png" type="image/png">
 <link rel="stylesheet" href="css/site.css?v=${VERSION}">${extraHead}
 <script>try{var l=new URLSearchParams(location.search).get('lang')||localStorage.getItem('yk-lang');if(l==='en'){document.documentElement.dataset.lang='en';document.documentElement.lang='en';}else{document.documentElement.dataset.lang='zh';document.documentElement.lang='zh-CN';}}catch(e){}</script>
</head>
<body data-page="${file}" data-title-zh="${escape(title.zh)} | Yichen Kong" data-title-en="${escape(title.en)} | Yichen Kong">
${navigation()}<main id="main">${body}</main>${footer()}${dialogs()}
<script type="module" src="js/site.js?v=${VERSION}"></script>
</body></html>\n`;
 fs.writeFileSync(path.join(root,file),html,'utf8');pages.push(file);
}
function scene(id,label,content,background='',className='',eager=false){
 return `<section class="scene ${className}" id="${id}" aria-label="${escape(label.zh)}" data-en-aria-label="${escape(label.en)}" data-zh-aria-label="${escape(label.zh)}">${background}<div class="scene-shade"></div><div class="scene-inner"><div class="scene-copy reveal">${content}</div></div></section>`;
}
const downloadRows=docs=>`<div class="document-list">${docs.map(d=>`<article><div>${heading(d.title,'h3')}${note(l(`PDF · ${toMb(fs.statSync(path.join(root,d.path)).size)}`,`PDF · ${toMb(fs.statSync(path.join(root,d.path)).size)}`))}</div><div class="document-actions">${button(l('在线查看','Read PDF'),d.path,'target="_blank" rel="noopener"')}${button(l('下载','Download'),d.path,'download')}</div></article>`).join('')}</div>`;
const simpleImage=(src,title,width,height)=>`<a class="zoom-image" href="${src}" data-gallery-image data-width="${width}" data-height="${height}" ${attr('aria-label','放大查看：'+title.zh,'Enlarge: '+title.en)}>${img(src,title,`width="${width}" height="${height}" loading="lazy"`)}<span>${t('放大查看','Enlarge')} ↗</span></a>`;
const albumCover=group=>{const item=itemsById[group.itemIds[0]];return `<a class="album-card" href="album-${group.id}.html">${img(item.thumbnail,item.title,`width="${item.previews[0].width}" height="${item.previews[0].height}" loading="lazy"`)}<div><h3>${t(group.title)}</h3><p>${t(group.region||l('拍摄记录','Field photographs'))} <span>· ${group.itemIds.length} ${t('张','images')}</span></p></div><span class="album-arrow" aria-hidden="true">↗</span></a>`;};

// HOME: each introduction is a viewport, not a grid of project cards.
const logoLockup=`<div class="identity-lockup reveal">
 ${img('assets/covers/logo.webp',l('LapLab 标志','LapLab logo'),'class="cover-logo" width="789" height="497" fetchpriority="high"')}
 <div class="identity-text"><h1>孔一宸</h1><p class="latin-name">YICHEN KONG</p>${para(site.location,'location')}${actions(button(l('了解我的 LOGO 与名称','About the logo & name'),'identity.html'))}</div></div>`;
let home=`<section class="scene identity-scene" id="profile">${cover('earth-sunset','center 63%',true)}<div class="scene-shade"></div><div class="scene-inner">${logoLockup}</div><a class="scroll-next" href="#about" ${attr('aria-label','下一页：个人简介','Next: about me')}><span></span></a></section>`;
home+=`<section class="scene about-scene" id="about">${cover('earth-blue','center 70%')}<div class="scene-shade"></div><div class="scene-inner about-layout"><div class="portrait-wrap reveal">${img('assets/covers/portrait-1280.webp',l('孔一宸','Yichen Kong'),'width="1706" height="1279" class="portrait" loading="lazy" srcset="assets/covers/portrait-640.webp 640w, assets/covers/portrait-1280.webp 1280w" sizes="(max-width:760px) 82vw, 38vw"')}</div><div class="about-copy reveal">${para(l('个人简介','About'),'eyebrow')}${heading(l('我目前仍是高中生。','I am currently a high school student.'),'h2')}${actions(button(l('查看简历','View CV'),'resume.html')+button(l('查看项目','View projects'),'#recoverable')+button(l('联系方式','Contact'),'#contact'))}</div></div></section>`;
home+=scene('recoverable',projects[0].title,para(projects[0].eyebrow,'eyebrow')+heading(projects[0].title)+para(projects[0].summary,'lead')+actions(button(l('项目详情','Explore project'),projects[0].href)+button(l('试验记录','Field tests'),projects[0].href+'#testing')),
 `<div class="aircraft-stage">${img('assets/covers/aircraft-airframe.webp',l('自主控制可回收探空飞行器 CAD 图','CAD drawing of the recoverable sounding aircraft'),'width="827" height="566" loading="lazy"')}</div>`,'aircraft-scene');
home+=scene('calculator',projects[1].title,para(projects[1].eyebrow,'eyebrow')+heading(projects[1].title)+para(projects[1].summary,'lead')+actions(button(l('项目详情','Explore project'),projects[1].href)+external(l('打开计算工具','Open calculator'),projects[1].external)),
 `<div class="calculator-stage">${img('assets/covers/calculator-1600.webp',l('计算工具界面','Calculator interface'),'width="1255" height="1366" loading="lazy"')}</div>`,'calculator-scene');
home+=scene('recognition',l('成果与荣誉','Recognition'),para(l('成果与荣誉 · 2025','Recognition · 2025'),'eyebrow')+heading(l('成果与荣誉','Achievements & honors'))+para(l('第40届全国青少年科技创新大赛中国科协主席奖及七项专项奖。其他竞赛、专利申请和检测记录在详情页列出。','CAST President’s Award and seven special awards at the 40th national youth innovation competition. Further competitions, patent application and testing records are listed inside.'),'lead')+actions(button(l('查看成果','View recognition'),'awards.html')),cover('honors','center 42%'),'recognition-scene');
home+=scene('qinghai',l('青海','Qinghai'),para(l('中国 · 青海省','Qinghai · China'),'eyebrow')+heading(l('青海','Qinghai'))+para(l('我生活的地方。这里收录青海的地理介绍、沱沱河试验地点和我拍摄的照片。','Where I live. A geographic introduction, the Tuotuohe test site and photographs I took.'),'lead')+actions(button(l('了解青海','Explore Qinghai'),'qinghai.html')+button(l('沱沱河','Tuotuohe'),'tuotuohe.html')),scenePhoto(itemsById['kunlun-hoh-xil']),'qinghai-scene');
home+=scene('discussion',l('留言与讨论','Discussion'),para(l('公开讨论','Public discussion'),'eyebrow')+heading(l('留言与讨论','Discussion'))+para(l('问题、建议，或关于项目的讨论。','Questions, suggestions, or a conversation about the projects.'),'lead')+actions(button(l('查看留言','Read discussion'),'discussion.html')+external(l('发表留言','Post a comment'),site.discussion))+note(l('由 GitHub Discussions 提供。阅读无需登录，发帖需 GitHub 账号。','Powered by GitHub Discussions. Read without signing in; a GitHub account is required to post.')),'','discussion-scene');
const contactItems=[
 [l('邮箱','Email'),'13997320897@163.com','mailto:13997320897@163.com'],
 [l('Gmail','Gmail'),'kyc13997320897@gmail.com','mailto:kyc13997320897@gmail.com'],
 [l('电话','Phone'),'+86 139 9732 0897','tel:+8613997320897'],
 [l('微信','WeChat'),'13997320897','#wechat-dialog'],
 [l('GitHub','GitHub'),'yichen-kong','https://github.com/yichen-kong'],
 [l('哔哩哔哩','Bilibili'),'研驰宸迹','https://space.bilibili.com/604998653'],
 [l('业余无线电呼号','Amateur-radio callsign'),site.callsign,'#radio-dialog']
];
home+=`<section class="scene contact-scene" id="contact"><div class="scene-inner"><div class="reveal">${para(l('联系方式','Contact'),'eyebrow')}${heading(l('联系','Get in touch'))}${para(l('点击对应项目可跳转；微信与呼号点击后查看详情。','Select a contact to open it. WeChat and the callsign open details.'),'lead')}</div><div class="contact-grid reveal">${contactItems.map(([label,value,url])=>`${url.startsWith('#')?`<button type="button" data-open-dialog="${url.slice(1)}"`:`<a href="${url}" ${url.startsWith('https')?'target="_blank" rel="noopener noreferrer"':''}`} class="contact-card"><span class="contact-label">${t(label)}</span><span class="contact-value">${escape(value)}</span><span class="contact-arrow" aria-hidden="true">↗</span>${url.startsWith('#')?'</button>':'</a>'}`).join('')}</div></div></section>`;
page('index.html',l('孔一宸','Yichen Kong'),home,{home:true});

// LOGO STORY — transcribed from the supplied Word document, not reinvented.
let identity=`<section class="page-intro"><div class="container">${crumbs(l('个人简介','About'),'index.html#about',l('LOGO 与名称','Logo & name'))}${para(l('个人标志','Personal identity'),'eyebrow')}${heading(l('我的 LOGO 与名称','My logo & name'),'h1')}${para(l('研驰宸迹 · Chen LapLab','Chen LapLab · 研驰宸迹'),'lead')}</div></section>`;
identity+=section('names',l('名称','Names'),`<div class="identity-grid"><div class="prose">${heading(l('研驰宸迹','研驰宸迹'),'h3')}${para(l('这是我在 B 站、知乎、嘉立创开源硬件平台等国内网站使用的昵称。“研”代表科研科创，“驰”代表我对汽车、赛车和骑行的热爱，“宸”取自我的名字。与“宸迹”组合，表达追寻理想、走出自己人生轨迹的愿望。','This is the name I use on Chinese platforms including Bilibili, Zhihu and the JLCPCB open-source hardware community. “研” refers to research, “驰” to my interest in cars, motorsport and cycling, and “宸” comes from my name. Together, the name expresses my wish to follow my interests and find my own path.'))}${heading(l('Chen LapLab','Chen LapLab'),'h3')}${para(l('在 YouTube、GitHub 等国际网站，我使用 Chen LapLab、Chen_LapLab 或 LapLab。“Chen”是“宸”的拼音；“Lap”是一圈，来自赛车运动；“Lab”是 Laboratory 的缩写。','On international platforms such as YouTube and GitHub, I use Chen LapLab, Chen_LapLab or LapLab. Chen is the pinyin of 宸, Lap is the unit of a racing circuit, and Lab is short for laboratory.'))}</div><figure class="brand-figure">${img('assets/covers/logo.webp',l('LapLab 标志','LapLab logo'),'width="789" height="497" loading="lazy"')}</figure></div>`);
identity+=section('symbol',l('标志','The mark'),`<div class="prose">${para(l('“Lap”与“Lab”的外形接近。左边的 L 借用了内燃机转速表的分段显示方式，颜色由低转速向高转速变化；右边分别是“ap”和“ab”。右下角为了视觉平衡，没有严格保持对称。','Lap and Lab have similar letterforms. The L on the left borrows the segmented display of an engine tachometer, with colors progressing from low to high revs. The right-hand forms are “ap” and “ab”; the lower-right corner departs from strict symmetry for visual balance.'))}${para(l('灵感来自数字分段式和液晶光条式仪表：从 Daytona、Corvette C4、Soarer、S2000，到 Reventón、RS6/7、720S、F80 和赛车方向盘。它们清晰、快速的转速显示，是我喜欢的设计。下方两张拼图来自我提供的说明文档，作为设计参考。','The inspiration is segmented digital and LCD-bar instrumentation: Daytona, Corvette C4, Soarer and S2000, followed by Reventón, RS6/7, 720S, F80 and racing steering wheels. I like their quick, readable RPM displays. The following collages are references included in my supplied design notes.'))}</div><div class="collage-gallery">${media.branding.filter(i=>i.id.includes('collage')).map(i=>`<figure>${simpleImage(i.src,l('仪表设计参考拼图','Instrument design reference collage'),i.width,i.height)}<figcaption>${t('图源：本人提供的 LOGO 说明文档；拼图中的参考图片非本人拍摄。','Source: my logo design notes; the reference photographs in the collages were not taken by me.')}</figcaption></figure>`).join('')}</div>${note(l('这些参考图片只用于说明标志的设计来源。','These reference images illustrate the origins of the mark.'))}`);
page('identity.html',l('我的 LOGO 与名称','My logo & name'),identity);

// CV — both languages always available, high fidelity previews without PDF plugin.
const resumeTabs=`<div class="cv-tabs" role="tablist" ${attr('aria-label','选择简历语言','CV language')}><button role="tab" id="cv-tab-zh" aria-controls="cv-panel-zh" aria-selected="true" data-cv-tab="zh">中文 PDF</button><button role="tab" id="cv-tab-en" aria-controls="cv-panel-en" aria-selected="false" tabindex="-1" data-cv-tab="en">English PDF</button></div>`;
let cv=`<section class="page-intro"><div class="container">${para(l('个人资料','Profile'),'eyebrow')}${heading(l('个人简历','Curriculum vitae'),'h1')}${para(l('可直接阅读中英文版本，也可下载原始 PDF。','Read either language here or download the original PDF.'),'lead')}${resumeTabs}</div></section>`;
cv+=`<div class="container cv-container">${media.resumes.map(r=>`<section class="cv-panel" role="tabpanel" id="cv-panel-${r.language}" aria-labelledby="cv-tab-${r.language}" ${r.language==='en'?'hidden':''}>${r.pages.map(p=>`<figure class="cv-page">${img(p.preview.src,l(`中文或英文简历第 ${p.page} 页`,`CV, page ${p.page}`),`width="${p.preview.width}" height="${p.preview.height}" loading="lazy"`)}<figcaption>${t(r.language==='zh'?l('中文简历','Chinese CV'):l('英文简历','English CV'))} · ${p.page}/${r.pageCount}</figcaption></figure>`).join('')}${actions(button(l('打开 PDF','Open PDF'),r.src,'target="_blank" rel="noopener"')+button(l('下载原始 PDF','Download original PDF'),r.src,'download'))}</section>`).join('')}${note(l('页面预览来自 PDF 原文件，不改写简历内容。','Previews are rendered from the supplied PDFs without rewriting their content.'))}</div>`;
page('resume.html',l('个人简历','Curriculum vitae'),cv);
page('documents.html',l('研究资料与简历','Documents & CV'),`<section class="page-intro"><div class="container">${para(l('公开资料','Documents'),'eyebrow')}${heading(l('研究资料与简历','Documents & CV'),'h1')}${para(l('中英文文件在两种界面中均可查看和下载。','All Chinese and English files are available in both interfaces.'),'lead')}</div></section>`+section('reports',l('研究报告','Research documents'),downloadRows(documents.filter(d=>d.type==='report')))+section('cv',l('简历','Curriculum vitae'),actions(button(l('阅读简历预览','Read CV preview'),'resume.html'))+downloadRows(documents.filter(d=>d.type==='cv'))));

// PROJECT PAGES — the flight tests belong to this project, not primary navigation.
let recoverable=scene('overview',projects[0].title,crumbs(l('项目','Projects'),'index.html#recoverable',projects[0].title)+para(projects[0].date,'eyebrow')+heading(projects[0].title,'h1')+para(l('系统设计、制造与试验记录。','System design, manufacture and testing.'),'lead'),`<div class="aircraft-stage">${img('assets/covers/aircraft-airframe.webp',l('飞行器结构图','Aircraft structure'),'width="827" height="566"')}</div>`,'aircraft-scene detail-hero');
recoverable+=section('system',l('系统概览','System overview'),`<div class="prose">${para(l('系统包括探空飞行器、通信链路、地面站和业务计算终端。由标准 750 g 高空气球搭载升空，设计为在约 30,000 m 高空分离，随后无动力滑翔返航。','The system consists of the sounding aircraft, radio link, ground station and operational calculator. A standard 750 g balloon provides ascent; the design separates at approximately 30,000 m and returns in an unpowered glide.'))}${para(l('研究、设计和制作由我独立完成。研究报告保留设计过程、仿真与试验资料；下载文件内容未因网页改名而修改。','I carried out the research, design and construction independently. The reports retain the design process, simulations and testing records; changing the website project name has not altered the source documents.'))}</div><div class="technical-list">${engineering.map(([h,p],i)=>`<article><span class="index-number">${String(i+1).padStart(2,'0')}</span><div>${heading(h,'h3')}${para(p)}</div></article>`).join('')}</div>`);
recoverable+=section('drawings',l('构型与结构','Configuration & structure'),`<div class="drawing-grid">${['airframe','balloon','profile','wing'].map((n,i)=>{const dims=[[827,566],[258,448],[507,124],[386,246]][i];return `<figure>${simpleImage(`assets/covers/aircraft-${n}.webp`,[l('结构剖视','Structure cutaway'),l('气球与飞行器','Balloon and aircraft'),l('机身侧视','Fuselage profile'),l('机翼展开构型','Wing configuration')][i],...dims)}<figcaption>${t([l('结构剖视','Structure cutaway'),l('气球搭载','Balloon configuration'),l('收拢状态','Stowed configuration'),l('机翼展开','Deployed wing')][i])}</figcaption></figure>`}).join('')}</div>${note(l('来源：本人提供的 SolidWorks 导出图。保持原比例；仅处理图外白底，不补画模型细节。现有导出分辨率较低。','Source: my SolidWorks exports. Original proportions retained; only the exterior white background is removed. No model details are generated. The available exports are low-resolution.'))}`);
recoverable+=section('testing',l('试验记录','Field testing'),`<div class="split-content"><div class="prose">${para(l('2026 年 7 月 19–22 日 · 沱沱河与三江源','19–22 July 2026 · Tuotuohe and Sanjiangyuan'),'eyebrow')}${para(l('在海拔约 4,534.5 m 的环境进行无人机带载低空测试和高空测试。关注低温、低压、湍流条件下的飞行器、控制和通信表现。','Drone-assisted low-altitude and high-altitude tests took place in an environment at approximately 4,534.5 m, examining aircraft, control and communications under cold, low-pressure and turbulent conditions.'))}${para(l('本人作为试飞负责人，在相关单位沟通和空域审批基础上组织试验。详细安排及可行性分析见试飞计划原文。','As the test lead, I organized the trials after coordination with relevant institutions and airspace approval. The original test plan contains the arrangements and feasibility analysis.'))}${actions(button(l('了解沱沱河','About Tuotuohe'),'tuotuohe.html')+button(l('试飞计划 · 英文 PDF','Test plan · English PDF'),'assets/docs/flight-test-plan-en.pdf','target="_blank" rel="noopener"'))}</div>${photo(itemsById['tuotuohe-01'],'wide-photo')}</div>`);
recoverable+=section('film',l('项目视频','Project film'),`<video class="project-video" controls playsinline preload="none" poster="assets/img/featured.jpg"><source src="assets/covers/project-preview.mp4" type="video/mp4"></video>${actions(external(l('查看原视频 · 341 MB','View original video · 341 MB'),'https://github.com/yichen-kong/yichen-kong.github.io/releases/download/media-originals-20261007/project-video-original.mp4'))}${note(l('默认播放压缩预览；原视频按需打开，不在页面加载时自动下载。','Playback uses a compressed preview. The original is only loaded when requested.'))}`);
recoverable+=section('reports',l('研究文件','Research documents'),downloadRows(documents.filter(d=>d.type==='report')));
page(projects[0].href,projects[0].title,recoverable);
let calculator=scene('overview',projects[1].title,crumbs(l('项目','Projects'),'index.html#calculator',projects[1].title)+para(l('网页应用','Web application'),'eyebrow')+heading(projects[1].title,'h1')+para(projects[1].summary,'lead')+actions(external(l('打开在线工具','Open live tool'),projects[1].external)),`<div class="calculator-stage">${img('assets/covers/calculator-1600.webp',l('计算工具界面','Calculator interface'),'width="1255" height="1366"')}</div>`,'calculator-scene detail-hero');
calculator+=section('method',l('模型与计算','Models & computation'),`<div class="prose">${para(l('工具内嵌 ISA 对流层和平流层模型，使用达因公式（按业务标定，二分法求解）、理想气体方程与气体比举力估算充气和上升参数。','The tool combines ISA tropospheric and stratospheric models, the operationally calibrated Dines formula solved by bisection, the ideal gas law and gas buoyancy to estimate inflation and ascent parameters.'))}${para(l('参考资料包括《常规高空气象观测业务规范》、WMO CIMO 指南和气球制造数据。ISA 是标准大气，不是现场实测大气；结果用于估算，不能代替业务规范和放飞安全判断。','References include operational upper-air observation specifications, the WMO CIMO Guide and balloon manufacturer data. ISA is a standard atmosphere, not a measurement of current conditions. Estimates do not replace operational procedures or launch-safety decisions.'))}</div>`);
calculator+=section('features',l('输入与输出','Inputs & outputs'),`<div class="technical-list">${[
 [l('输入','Inputs'),l('气球标称克重、实际克重补偿、载荷、目标升速、气体类型和纯度，以及测站温度与气压。支持滑块与键盘输入。','Balloon mass and mass compensation, payload, target ascent rate, gas type and purity, station temperature and pressure. Sliders and keyboard entry are supported.')],
 [l('计算与显示','Calculation & display'),l('估算地面充气体积、净举力、内外压差、温压密度，以及对流层顶和爆炸高度。SVG 图形显示放飞和上升节点。','Estimates fill volume, net lift, pressure difference, temperature, pressure, density, tropopause and burst altitude. SVG graphics show launch and ascent stages.')],
 [l('提示与记录','Warnings & records'),l('提供膨胀余量、低温脆性、涡街、积冰和纯度相关的基础提示，可关闭。可生成 ASCII 操作台账。','Optional basic checks cover expansion margin, cold brittleness, vortex shedding, icing and gas purity. An ASCII operation log can be generated.')],
 [l('实现与局限','Implementation & limits'),l('React 与 Tailwind 构建的纯前端响应式应用，支持中英文。状态钩子绑定参数、缓存钩子封装计算。动画和时间估计仍有已知误差。','A responsive front-end application built with React and Tailwind, with Chinese and English interfaces. State hooks bind inputs and memoization wraps calculations. Animation and timing estimates still have known inaccuracies.')]
 ].map(([a,b])=>`<article><div>${heading(a,'h3')}${para(b)}</div></article>`).join('')}</div>${actions(external(l('使用计算工具','Use the calculator'),projects[1].external))}`);
page(projects[1].href,projects[1].title,calculator);

let honors=scene('top',l('成果与荣誉','Recognition'),para(l('成果与荣誉 · 2025','Recognition · 2025'),'eyebrow')+heading(l('成果与荣誉','Achievements & honors'),'h1')+para(l('竞赛、专利申请与测试记录。','Competitions, patent application and testing records.'),'lead'),cover('honors','center 42%',true),'recognition-scene detail-hero');
honors+=section('competition',l('第40届全国青少年科技创新大赛','40th national youth science & technology innovation contest'),`<ol class="award-list">${awards.map((a,i)=>`<li>${i===0?'<span class="award-highlight">':''}${t(a)}${i===0?'</span>':''}</li>`).join('')}</ol>${note(l('2025 年。奖项名称以证书和原始简历为准。','2025. Award names follow the certificates and supplied CV.'))}`);
honors+=section('results',l('其他成果','Other results'),`<div class="technical-list">${otherResults.map(([a,b])=>`<article><div>${heading(a,'h3')}${para(b)}</div></article>`).join('')}</div>`);
honors+=section('photos',l('证书与照片','Certificates & photographs'),`<div class="award-gallery">${[1,2,3,4].map(i=>{const dims=[[1500,2000],[4096,3072],[4096,3072],[4096,3072]][i-1];return simpleImage(`assets/img/award-${i}.jpg`,l(`获奖照片 ${i}`,`Award photograph ${i}`),...dims)}).join('')}</div>`);
page('awards.html',l('成果与荣誉','Achievements & honors'),honors);

const globeBlock=`<div class="geo-layout"><div class="geo-frame" data-earth><p class="geo-loading">${t('地球视图正在加载…','Loading Earth view…')}</p></div><div class="geo-copy">${heading(l('青海在地球上的位置','Qinghai on Earth'),'h2')}${para(l('位于青藏高原东北部。地球图标记青海及西宁；太阳光照和晨昏线按当前 UTC 时间计算。','On the northeastern Tibetan Plateau. The globe marks Qinghai and Xining; sunlight and the terminator follow current UTC time.'))}<p class="geo-date" data-utc-time></p>${note(l('可拖动旋转，也可暂停。数据说明见视图下方。','Drag to rotate or pause the animation. Data notes are provided below the view.'))}</div></div>`;
let qinghai=scene('top',l('青海省','Qinghai'),para(l('中国 · 青海省','Qinghai · China'),'eyebrow')+heading(l('青海省','Qinghai'),'h1')+para(l('省会西宁，位于青藏高原东北部。','Capital: Xining. Northeastern Tibetan Plateau.'),'lead')+actions(button(l('地理介绍','Geography'),'#geography')+button(l('摄影图册','Photo albums'),'#albums')),scenePhoto(itemsById['kunlun-hoh-xil'],true),'qinghai-scene detail-hero');
qinghai+=section('geography',l('地理概览','Geographic overview'),`<div class="facts-grid"><article>${heading(l('位置与地形','Location & terrain'),'h3')}${para(l('青海位于中国西部。昆仑山、祁连山、柴达木盆地和高原腹地构成多样的地形；不同区域的海拔和气候差异很大。','Qinghai is in western China. The Kunlun and Qilian mountains, Qaidam Basin and plateau interior form varied terrain; elevation and climate differ substantially by area.'))}</article><article>${heading(l('河流与湖泊','Rivers & lakes'),'h3')}${para(l('长江、黄河与澜沧江的源区位于青海。青海湖位于省内东北部；柴达木盆地有察尔汗等盐湖。','Qinghai contains headwaters of the Yangtze, Yellow and Lancang rivers. Qinghai Lake is in the northeast of the province; the Qaidam Basin contains salt lakes including Qarhan.'))}</article><article>${heading(l('城市与交通','Cities & transport'),'h3')}${para(l('西宁是省会，格尔木是青藏交通的重要节点。青藏铁路和 G109 国道经过昆仑山口、沱沱河一带通往西藏。','Xining is the provincial capital and Golmud a transport hub. The Qinghai–Tibet railway and G109 pass through the Kunlun Pass and Tuotuohe region toward Tibet.'))}</article></div>`);
qinghai+=section('qinghai-lake',l('青海湖','Qinghai Lake'),`<div class="source-feature"><figure>${img('assets/external/qinghai-lake-nasa.jpg',l('青海湖卫星影像','Satellite view of Qinghai Lake'),'width="1469" height="979" loading="lazy"')}<figcaption>${t('图源：NASA Earth Observatory / Allison Nussbaum，使用 USGS Landsat 数据。','Source: NASA Earth Observatory / Allison Nussbaum, using USGS Landsat data.')} <a href="https://science.nasa.gov/earth/earth-observatory/shifting-sand-spits-151316/" target="_blank" rel="noopener">${t('原文 ↗','Source ↗')}</a></figcaption></figure><div class="prose">${heading(l('青海湖','Qinghai Lake'),'h2')}${para(l('中国最大的内陆咸水湖，位于青海省东北部。它是高原水文、候鸟迁徙和区域生态变化的重要地理对象。','China’s largest inland saltwater lake, in northeastern Qinghai. It is a major geographic feature for plateau hydrology, migratory birds and regional ecological change.'))}</div></div>`);
qinghai+=`<section class="content-section geo-section" id="earth"><div class="container">${globeBlock}</div></section>`;
qinghai+=section('terrain',l('青海 3D 地形','Qinghai terrain in 3D'),`${para(l('真实高程数据制作的可旋转地形。覆盖范围、垂直夸张比例和数据来源在视图中标出。','Rotatable terrain from measured elevation data. Coverage, vertical exaggeration and sources are stated in the view.'),'lead')}<div class="terrain-frame" data-terrain><p class="geo-loading">${t('地形正在加载…','Loading terrain…')}</p></div>`);
const qhGroups=media.groups.filter(g=>g.id!=='tuotuohe'&&g.id!=='hexicorridor');
qinghai+=section('albums',l('我的摄影图册','My photo albums'),`${para(l('按拍摄地点整理。先加载小体积预览；每张照片都提供未经改动的原文件。','Organized by location. Lightweight previews load first; every photograph has an unmodified original-file link.'),'lead')}<div class="album-index">${qhGroups.map(albumCover).join('')}</div>${heading(l('邻近地区','Neighboring regions'),'h3')}${note(l('以下是同次行程中的甘肃照片，不归为青海省内。','The following Gansu photographs were taken on the same trip; they are not labeled as places in Qinghai.'))}<div class="album-index">${media.groups.filter(g=>g.id==='hexicorridor').map(albumCover).join('')}</div>`);
qinghai+=section('tuotuohe',l('沱沱河','Tuotuohe'),`<div class="split-content">${photo(itemsById['tuotuohe-01'],'wide-photo')}<div class="prose">${para(l('我的探空系统试验地点。了解河流、气象站和现场记录。','The test location for my sounding system. Read about the river, meteorological station and field records.'))}${actions(button(l('进入沱沱河页面','Visit Tuotuohe'),'tuotuohe.html'))}</div></div>`);
page('qinghai.html',l('青海省','Qinghai'),qinghai);
let tuotuohe=scene('top',l('沱沱河','Tuotuohe'),crumbs(l('青海','Qinghai'),'qinghai.html',l('沱沱河','Tuotuohe'))+para(l('青海 · 长江源区','Qinghai · Yangtze headwaters'),'eyebrow')+heading(l('沱沱河','Tuotuohe'),'h1')+para(l('我的探空系统试验地点。','The field-test location for my sounding system.'),'lead'),scenePhoto(itemsById['tuotuohe-01'],true),'qinghai-scene detail-hero');
tuotuohe+=section('place',l('地点与气象站','The place & weather station'),`<div class="prose">${para(l('沱沱河位于青藏高原腹地的长江源区，青藏公路与铁路经此通过。高海拔、低温和稀薄空气，使这里与低海拔测试环境很不一样。','Tuotuohe lies in the Yangtze headwater region of the Tibetan Plateau, on the Qinghai–Tibet road and railway routes. High elevation, cold and thin air make it very different from low-altitude test environments.'))}${para(l('沱沱河气象站海拔约 4,533 米，是全国第二高的探空站。该表述来自青海省气象局公开材料；不同公开报道的海拔四舍五入值略有差异。','Tuotuohe Meteorological Station is about 4,533 m above sea level and is described in Qinghai Meteorological Bureau material as the second-highest sounding station in China. Public reports round the elevation slightly differently.'))}<p><a href="https://qh.cma.gov.cn/zfxxgk/zwgk/czzj/bmyjsxx/202408/W020240828559689971028.pdf" target="_blank" rel="noopener">${t('青海省气象局公开材料 ↗','Qinghai Meteorological Bureau source ↗')}</a></p>${note(l('站点介绍与个人试验记录分开列示；不将网站内容视作气象站官方发布。','Station information and personal test records are presented separately; this website is not an official station publication.'))}</div>`);
tuotuohe+=section('visit',l('我的现场记录','My field record'),`<div class="split-content"><div class="prose">${para(l('2026 年 7 月 19–22 日，我在沱沱河与三江源开展自主控制可回收探空系统的低空和高空试验。试验内容、审批沟通及技术文件归入项目页。','On 19–22 July 2026, I conducted low- and high-altitude trials of the autonomous recoverable sounding system in the Tuotuohe and Sanjiangyuan region. Test details, coordination and technical files belong to the project page.'))}${actions(button(l('查看项目试验记录','Read the project test record'),projects[0].href+'#testing')+button(l('查看沱沱河图册','Open Tuotuohe album'),'album-tuotuohe.html'))}</div>${photo(itemsById['tuotuohe-04'],'wide-photo')}</div>`);
page('tuotuohe.html',l('沱沱河','Tuotuohe'),tuotuohe);

// Albums are discrete places; exact source files are Release assets, never downloaded automatically.
for(const group of media.groups){
 const cards=group.itemIds.map(id=>itemsById[id]).map(item=>`<figure class="album-photo" id="${item.id}">
 <a href="${item.src}" data-gallery-image data-gallery-id="${item.id}" data-width="${item.previews.at(-1).width}" data-height="${item.previews.at(-1).height}" ${attr('aria-label','放大查看：'+item.title.zh,'Enlarge: '+item.title.en)}>${photo(item)}<span class="enlarge-label">${t('放大预览','Enlarge preview')} ↗</span></a>
 <figcaption><div>${heading(item.title,'h2')}${para(item.caption)}${note(l('拍摄：孔一宸','Photography: Yichen Kong'))}</div><div class="original-actions">${external(l('查看原图','View original'),item.original.url)}<span>${item.width.toLocaleString('en-US')} × ${item.height.toLocaleString('en-US')} · ${toMb(item.original.bytes)}</span>${item.deepZoom?`<button class="button" data-open-panorama>${t('高清全景浏览','Explore full-resolution panorama')} ↗</button>`:''}</div></figcaption></figure>`).join('');
 page(`album-${group.id}.html`,group.title,`<section class="page-intro album-intro"><div class="container">${crumbs(l('青海图册','Qinghai albums'),'qinghai.html#albums',group.title)}${para(group.region||l('拍摄记录','Photographs'),'eyebrow')}${heading(group.title,'h1')}${para(l(`${group.itemIds.length} 张照片 · 拍摄：孔一宸`,`${group.itemIds.length} photographs · Yichen Kong`),'lead')}${note(l('图片为快速预览。点击可缩放；“查看原图”打开未经重编码的原文件。','These are fast previews. Select one to zoom; “View original” opens the unmodified source file.'))}</div></section><section class="content-section"><div class="container album-photos">${cards}</div></section>`);
}
page('discussion.html',l('留言与讨论','Discussion'),`<section class="page-intro"><div class="container">${para(l('公开讨论','Public discussion'),'eyebrow')}${heading(l('留言与讨论','Discussion'),'h1')}${para(l('欢迎留下问题、建议，或讨论项目。','Questions, suggestions and project discussions are welcome.'),'lead')}${actions(external(l('在 GitHub 发表留言','Post on GitHub'),site.discussion))}${note(l('完全免费。阅读无需登录，发表与回复需要 GitHub 账号；内容会公开显示。请勿发布个人敏感信息。','Free of charge. Reading requires no sign-in; posting and replying require a GitHub account. Content is public; please do not share sensitive personal information.'))}</div></section><section class="content-section"><div class="container discussion-container" data-discussion></div></section><section class="content-section"><div class="container prose">${heading(l('服务与隐私','Service & privacy'),'h2')}${para(l('讨论存储于本网站的 GitHub Discussions，不是邮件草稿，也不是仅保存在你浏览器里的留言。此页显示最近同步的公开内容；最新评论以原讨论页为准。','Discussions are stored in this website’s GitHub Discussions—not an email draft or browser-only record. This page shows recently synchronized public content; the original thread contains the latest comments.'))}${para(l('本服务不能匿名发帖。国内部分网络访问 GitHub 可能不稳定，因此这里保留可直接阅读的同步内容；无法承诺任意地区始终可用。','Anonymous posting is not supported. GitHub may be unreliable on some networks in mainland China, so synchronized content remains readable here. Availability in every region cannot be guaranteed.'))}</div></section>`);
page('research.html',l('项目','Projects'),`<section class="page-intro"><div class="container">${heading(l('项目','Projects'),'h1')}</div></section>${projects.map(p=>section(p.id,p.title,para(p.summary,'lead')+actions(button(l('项目详情','Explore project'),p.href)))).join('')}`);
page('field-tests.html',l('试验记录','Field tests'),`<section class="page-intro"><div class="container">${heading(l('试验记录已归入项目页','Field tests are part of the project'),'h1')}${actions(button(l('查看试验记录','View field tests'),projects[0].href+'#testing'))}</div></section>`,{extraHead:`<meta http-equiv="refresh" content="0;url=${projects[0].href}#testing">`});
page('sources.html',l('图源与说明','Sources & notes'),`<section class="page-intro"><div class="container">${heading(l('图源与说明','Sources & notes'),'h1')}</div></section>${section('credits',l('影像与数据','Images & data'),`<div class="prose">${para(l('个人照片、青海与沱沱河图册由孔一宸提供并拍摄。项目 CAD 图、视频、证书和简历来自本人资料。','Personal photographs and the Qinghai/Tuotuohe albums were supplied and photographed by Yichen Kong. Project CAD exports, video, certificates and CVs are from his materials.'))}${para(l('封面地球影像来自 NASA Image and Video Library，编号 iss072e724819。日落与蓝调使用同一照片的不同调色版本，不代表两次独立观测。','The cover Earth photograph is NASA Image and Video Library image iss072e724819. Sunset and blue-hour treatments use the same photograph with different color grading; they are not two separate observations.'))}<p><a href="https://images.nasa.gov/details/iss072e724819" target="_blank" rel="noopener">NASA · iss072e724819 ↗</a></p>${para(l('地球和地形视图的数据来源及处理方法随组件标注。仪表拼图来自用户提供的 Word 说明文档，其中参考照片非本人拍摄。','Earth and terrain data sources and processing methods are identified with the views. Instrument collages come from the supplied Word design notes; their reference photographs were not taken by the site owner.'))}${para(l('图册预览采用压缩版本，原文件保留其字节和分辨率。西宁全景以分块方式按需加载，最高层保留原始像素尺寸。','Album previews are compressed derivatives; original files retain their bytes and resolution. Xining panorama tiles load on demand and the top level retains the original pixel dimensions.'))}</div>`)}`);
// Production output is an explicit allowlist: no backups, private manifests, keys, scripts or git.
for(const dir of ['css','js','assets'])fs.cpSync(path.join(root,dir),path.join(out,dir),{recursive:true});
fs.mkdirSync(path.join(out,'assets/data'),{recursive:true});
fs.writeFileSync(path.join(root,'assets/data/gallery.json'),JSON.stringify(media));
fs.writeFileSync(path.join(out,'assets/data/gallery.json'),JSON.stringify(media));
const snapshotFile=path.join(root,'content/discussions.json');
if(fs.existsSync(snapshotFile)){
 fs.copyFileSync(snapshotFile,path.join(root,'assets/data/discussions.json'));
 fs.copyFileSync(snapshotFile,path.join(out,'assets/data/discussions.json'));
}
for(const file of pages)fs.copyFileSync(path.join(root,file),path.join(out,file));
fs.writeFileSync(path.join(out,'.nojekyll'),'');
fs.writeFileSync(path.join(root,'content/generated-pages.json'),JSON.stringify(pages,null,2)+'\n');
console.log(`Built ${pages.length} UTF-8 pages into public/.`);
